name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.20", "3.10.15", "3.11.10", "3.12.7", "3.13.0"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: npm install -g elm
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv run python -m pytest
